### ISSUE TITLE
apply_styles method on sheet

### ISSUE THREAD

**Issue by westonganger** [sakovias/axlsx_styler#9] opened 2016-06-18 20:14 UTC
In my gem SpreadsheetArchitect I have the ability to create axlsx sheets individually. I was wondering if we can get the `workbook.apply_styles` to also be available as `sheet.apply_styles` so that I can apply the styling before returning the sheet.

**Comment by sakovias** [comment] 2016-06-18 21:33
If you work with vanilla `axlsx`, you probably still need to call `axlsx.serialize <my_workbook>` when you're done with the whole workbook (all the worksheets included) to have it processed and saved as `.xlsx` file.  If I understand it correctly, `axlsx` sets styles on the entire workbook, which is something I can't change.

As far as `axlsx_styler` goes, I think there's an opportunity to hide the call `workbook.apply_styles` from the end user. Would it solve your problem? Fell free to use examples to help me understand where your problem is.

**Comment by westonganger** [comment] 2016-06-18 22:44
I think hiding that might solve the issue. How would it work though?

**Comment by sakovias** [comment] 2016-06-18 23:34
It's possible that we can patch `axlsx.serialize`, but I don't know for sure yet.

**Comment by westonganger** [comment] 2016-06-18 23:57
I like that idea. Make sure to also patch the `to_stream` method. I use this method instead of serialize so that I don't have to save to a file.

**Comment by westonganger** [comment] 2016-06-19 00:13
We could do it like this:

```ruby
module AxlsxStyler
  module Axlsx
    module Package

      original_serialize = instance_method(:serialize)

      define_method :serialize do
        @workbook.apply_styles
        old_serialize.bind(self).()
      end

      original_to_stream = instance_method(:to_stream)

      define_method :to_stream do
        @workbook.apply_styles
        original_to_stream.bind(self).()
      end

    end
  end
end
```

I read this method of patching from this stackoverflow post http://stackoverflow.com/questions/4470108/when-monkey-patching-a-method-can-you-call-the-overridden-method-from-the-new-i

**Comment by sakovias** [comment] 2016-06-19 00:25
Thanks for the example. I will look at it some time next week.

In the meantime it would be great to know what is the root cause of your problems. `workbook.apply_styles` should work, as all styles (even in the original `axlsx`) are defined on the workbook, not on its worksheets.

**Comment by westonganger** [comment] 2016-06-19 00:27
Sorry I should have mentioned that its not an issue. I was just wondering if that method could possibly done on the sheet level but you say that's not possible so that's okay with me.

**Comment by sakovias** [comment] 2016-06-19 16:17
Ah, good. I'm just going to close this one then.

**Closed by sakovias** 2016-06-19 16:17 UTC

**Comment by westonganger** [comment] 2016-06-19 17:10
Are you still going to try and hide the call to `apply_styles`?

**Comment by sakovias** [comment] 2016-06-19 20:28
I thought to slack away for a bit, but you're puting me on the spot :smile: 

Could you please review [this change](https://github.com/sakovias/axlsx_styler/pull/10)?

**Comment by sakovias** [comment] 2016-06-19 20:35
Also, if you want to make your own PR, please feel free to do so.
